# 命令执行根目录，此处可以为空，为空会被替换为 one-click-executor.dir
dir: D:\Projects\wms\wms3.0\#{[mode]}
# 日志错误关键词（判断是否命令是否成功执行）
errorLogWords: ["abort", "error", "fail", "unable", "Could not"]
# 启用替换id
enableRefId: [
      "wms2-dev",
]
enableAddItemIfNotExists: true
# 替换配置文件相对地址
filePaths: [
  wms-cloud/wms-service-in/src/main/resources/bootstrap.yml,
  wms-cloud/wms-service-open/src/main/resources/bootstrap.yml,
  wms-cloud/wms-service-order/src/main/resources/bootstrap.yml,
  wms-cloud/wms-service-out/src/main/resources/bootstrap.yml,
  wms-cloud/wms-service-query/src/main/resources/bootstrap.yml,
  wms-cloud/wms-service-sap/src/main/resources/bootstrap.yml,
  wms-cloud/wms-service-base/src/main/resources/bootstrap.yml
]
# 配置项map，优先级最高
propertiesMap: {
  "spring.config.location":"file:D:/zyj/resource/config/config_wms3/#{[mode]}_default/${spring.application.name}.yaml,file:D:/zyj/resource/config/config_wms3/common/common.yaml,file:D:/zyj/resource/config/config_wms3/#{[mode]}/${spring.application.name}.yaml"
}
# 需要注释的配置项，优先级最高
uselessProperties: [
]
# 替换关键字描述
replaceKeys: [
  {
    # web环境配置
    refId: "wms2-dev",
    propertiesMap: {
    }
  }
]

